@startuml C4_Component_ToBeSystem_UserService

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

Container(web_app, "Web App", "", "")
Container(api_gateway, "API Gateway", "", "Роутинг + Авторизация")

ContainerDb(user_db, "User DB", "PostgreSQL", "")

Container_Boundary(user_service, "User Service") {
    Component(auth_controller, "Аутентификация", "", "REST API для аутентификации")
    Component(session_controller, "Сессии", "", "REST API для управления сессиями")
    Component(user_controller, "Пользователи", "", "REST API для управления пользователями")
}

Rel(web_app, api_gateway, "Аутентификация, Сессии, Пользователи", "https")
Rel(api_gateway, auth_controller, "Авторизация", "http")
Rel(api_gateway, user_controller, "Пользователи", "http")
Rel(api_gateway, session_controller, "Сессии", "http")

Rel(auth_controller, user_db, "query", "")
Rel(session_controller, user_db, "query", "")
Rel(user_controller, user_db, "query", "")

@enduml

@startuml C4_Component_ToBeSystem_DeviceService

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

Container_Boundary(device_service, "Device Service") {
}

ContainerDb(device_db, "Device DB", "PostgreSQL", "")

@enduml

@startuml C4_Component_ToBeSystem_IntegrationService

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

Container_Boundary(integration_service, "Integration Service") {
    Component(command_handler, "Command Handler", "", "Обработка команд к устройствам")
    Component(event_handler, "Event Handler", "", "Обработка событий от устройств")

    Component(device_config, "Device Config", "", "Конфигурация устройств")
    Component(device_config_cache, "Device Config Cache", "", "Кэш конфигурации устройств")
    Component(router, "Router", "", "Маршрутизация запросов к адаптерам")

    Component(mqtt_adapter, "MQTT Adapter", "", "Работа с MQTT устройствами")
    Component(http_adapter, "HTTP Adapter", "", "Работа с HTTP устройствами")
}

Container_Boundary(Kafka, "Kafka") {
    Component(kafka_device_events, "device.events Topic", "Kafka", "")
}

Container(device_service, "Device Service", "", "")

Rel(device_service, command_handler, "Выполнение команд", "http")
Rel(command_handler, device_config, "Получение конфигурации устройства", "")
Rel(device_config, device_config_cache, "Получение конфигурации устройства (кэш)", "")
Rel(device_config, device_service, "Получение конфигурации об устройстве", "")

System_Ext(mqtt_device, "MQTT Device", "Девайсы с общением по MQTT.")
System_Ext(http_device, "HTTP Device", "Девайсы с общением по HTTP.")


Rel(command_handler, router, "Маршрутизация команд", "")
Rel(router, mqtt_adapter, "Команды MQTT", "")
Rel(router, http_adapter, "Команды HTTP", "")

Rel(mqtt_adapter, mqtt_device, "MQTT")
Rel(http_adapter, http_device, "HTTP")

Rel(mqtt_adapter, event_handler, "События MQTT", "")
Rel(http_adapter, event_handler, "События HTTP", "")

Rel(event_handler, kafka_device_events, "Публикация событий устройств", "")

@enduml


' Automation Service

@startuml C4_Component_ToBeSystem_AutomationService

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

Person(user, "User", "Пользователь системы")
Container(web_app, "Web App", "", "")
Container(api_gateway, "API Gateway", "", "Роутинг + Авторизация")
Container(integration_service, "Integration Service", "", "Интеграция с устройствами")
ContainerDb(automation_db, "Automation DB", "PostgreSQL", "")

Container_Boundary(automation_service, "Automation Service") {
    Component(scenario_handler, "Scenario Handler", "", "Управление сценариями автоматизации")
    Component(scenario_engine, "Scenario Engine", "", "Выполнение сценариев автоматизации")
}

Rel(user, web_app, "Использует", "https")
Rel(web_app, api_gateway, "Управление сценариями", "https")
Rel(api_gateway, scenario_handler, "Управление сценариями", "http")

Container_Boundary(Kafka, "Kafka") {
    Component(kafka_device_events, "device.events Topic", "Kafka", "")
}

Rel(scenario_handler, automation_db, "Чтение/запись сценариев" , "http")
Rel(scenario_engine, automation_db, "Чтение/запись данных сценариев", "http")
Rel(scenario_engine, kafka_device_events, "Подписка на события устройств", "http")
Rel(scenario_engine, integration_service, "Отправка команд устройствам", "http")

@enduml
